version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/coding/testingtesttest/
    steps:
      - checkout
      - run: npm install
      - run: npm test